apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    envTemplate:
      template: "{{.DOCKER_REGISTRY}}/dcole-inviqa/hello-world:{{.VERSION}}"
  artifacts:
  - imageName: changeme
    workspace: .
    docker: {}
  local: {}
deploy:
  kubectl:
    manifests:
profiles:
- name: dev
  build:
    tagPolicy:
      envTemplate:
        template: "{{.DOCKER_REGISTRY}}/dcole-inviqa/hello-world:{{.DIGEST_HEX}}"
    artifacts:
    - docker: {}
    local: {}
  deploy:
    helm:
      releases:
      - name: hello-world
        chartPath: charts/hello-world
        setValueTemplates:
          image.repository: "{{.DOCKER_REGISTRY}}/dcole-inviqa/hello-world"
          image.tag: "{{.DIGEST_HEX}}"
